=== Dragon7k/Epam_Task2/src/test/resources/file/devices.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.org/devices"
        xmlns:tns="http://www.example.org/devices"
        elementFormDefault="qualified">

    <element name="Devices">
        <complexType>
            <sequence>
                <element ref="tns:Device" maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>

    <complexType name="Device">
        <sequence>
            <element name="name" type="string" />
            <element name="baseInfo" type="tns:BaseInfo" />
            <element name="deviceType" type="tns:DeviceType" />
            <element name="origin" type="string" />
            <element name="release" type="gYearMonth" />
            <element name="price" type="tns:Price" />
            <element name="isCritical" type="boolean" />
        </sequence>
        <attribute name="id" type="tns:DeviceID" use="required" />
    </complexType>

    <complexType name="BaseInfo">
        <all>
            <element name="producer" type="string"></element>
            <element name="model" type="string"></element>
            <element name="serial" type="string"></element>
        </all>
    </complexType>

    <simpleType name="DeviceType">
        <restriction base="string">
            <enumeration value="integrated"></enumeration>
            <enumeration value="peripheral"></enumeration>
        </restriction>
    </simpleType>

    <simpleType name="Price">
        <restriction base="positiveInteger">
            <maxInclusive value="10000"></maxInclusive>
        </restriction>
    </simpleType>
    <simpleType name="Size">
        <restriction base="positiveInteger">
            <maxInclusive value="32"></maxInclusive>
        </restriction>
    </simpleType>

    <simpleType name="DeviceID">
        <restriction base="ID">
            <pattern value="d[0-9]{1,10}"></pattern>
        </restriction>
    </simpleType>

    <complexType name="Processor">
        <complexContent>
            <extension base="tns:Device">
                <sequence>
                    <element name="codeName" type="string" />
                    <element name="frequency" type="positiveInteger" />
                    <element name="power" type="string" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="GraphicsCard">
        <complexContent>
            <extension base="tns:Device">
                <sequence>
                    <element name="size" type="tns:Size"></element>
                    <element name="power" type="string" />
                    <element name="isCooler" type="boolean"></element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>


    <complexType name="Mouse">
        <complexContent>
            <extension base="tns:Device">
                <sequence>
                    <element name="portType" type="tns:PortType" />
                    <element name="connectionType" type="tns:ConnectionType" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="PortType">
        <restriction base="string">
            <enumeration value="lpt"></enumeration>
            <enumeration value="com"></enumeration>
            <enumeration value="usb"></enumeration>
            <enumeration value="ps_2"></enumeration>
        </restriction>
    </simpleType>

    <simpleType name="ConnectionType">
        <restriction base="string">
            <enumeration value="wired"></enumeration>
            <enumeration value="wireless"></enumeration>
        </restriction>
    </simpleType>

    <element name="Device" type="tns:Device" abstract="true" />
    <element name="Processor" type="tns:Processor"
             substitutionGroup="tns:Device" />
    <element name="GraphicsCard" type="tns:GraphicsCard"
             substitutionGroup="tns:Device" />
    <element name="Mouse" type="tns:Mouse"
             substitutionGroup="tns:Device" />
</schema>

=== Dragon7k/Epam_Task2/src/main/resources/file/devices.xml
<?xml version="1.0" encoding="UTF-8"?>
<Devices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.org/devices"
         xsi:schemaLocation="http://www.example.org/devices devices.xsd">
    <Processor id="d1">
        <name>processor1</name>
        <baseInfo>
            <producer>Intel</producer>
            <model>Core i5</model>
            <serial>654682</serial>
        </baseInfo>
        <deviceType>integrated</deviceType>
        <origin>Vietnam</origin>
        <release>2019-01</release>
        <price>50</price>
        <isCritical>true</isCritical>
        <codeName>codeName1</codeName>
        <frequency>2400</frequency>
        <power>30</power>
    </Processor>
    <Processor id="d2" >
        <name>processor2</name>
        <baseInfo>
            <producer>AMD</producer>
            <model>AMDModel</model>
            <serial>12384163</serial>
        </baseInfo>
        <deviceType>integrated</deviceType>
        <origin>Taiwan</origin>
        <release>2020-07</release>
        <price>40</price>
        <isCritical>true</isCritical>
        <codeName>codeName2</codeName>
        <frequency>2500</frequency>
        <power>20</power>
    </Processor>
    <Processor id="d3">
        <name>processor3</name>
        <baseInfo>
            <producer>Intel</producer>
            <model>Core i3</model>
            <serial>6545482</serial>
        </baseInfo>
        <deviceType>integrated</deviceType>
        <origin>Vietnam</origin>
        <release>2019-08</release>
        <price>50</price>
        <isCritical>true</isCritical>
        <codeName>codeName3</codeName>
        <frequency>2100</frequency>
        <power>20</power>
    </Processor>
    <Processor id="d4">
        <name>processor4</name>
        <baseInfo>
            <producer>Intel</producer>
            <model>Core i7</model>
            <serial>785522</serial>
        </baseInfo>
        <deviceType>integrated</deviceType>
        <origin>Vietnam</origin>
        <release>2020-08</release>
        <price>80</price>
        <isCritical>true</isCritical>
        <codeName>codeName4</codeName>
        <frequency>3000</frequency>
        <power>60</power>
    </Processor>
    <Processor id="d5" >
        <name>processor5</name>
        <baseInfo>
            <producer>AMD</producer>
            <model>AMDModel</model>
            <serial>84651</serial>
        </baseInfo>
        <deviceType>integrated</deviceType>
        <origin>China</origin>
        <release>2020-02</release>
        <price>50</price>
        <isCritical>true</isCritical>
        <codeName>codeName5</codeName>
        <frequency>2400</frequency>
        <power>40</power>
    </Processor>
    <GraphicsCard id="d6" >
        <name>graphicCard1</name>
        <baseInfo>
            <producer>Asus</producer>
            <model>gtx1650</model>
            <serial>123432</serial>
        </baseInfo>
        <deviceType>integrated</deviceType>
        <origin>China</origin>
        <release>2020-05</release>
        <price>40</price>
        <isCritical>true</isCritical>
        <size>4</size>
        <power>40</power>
        <isCooler>true</isCooler>
    </GraphicsCard>
    <GraphicsCard id="d7">
        <name>graphicCard2</name>
        <baseInfo>
            <producer>MSI</producer>
            <model>gt730</model>
            <serial>4563241</serial>
        </baseInfo>
        <deviceType>integrated</deviceType>
        <origin>China</origin>
        <release>2021-11</release>
        <price>40</price>
        <isCritical>true</isCritical>
        <size>8</size>
        <power>60</power>
        <isCooler>false</isCooler>
    </GraphicsCard>
    <GraphicsCard id="d8">
        <name>graphicCard3</name>
        <baseInfo>
            <producer>GYGABYTE</producer>
            <model>gtx720</model>
            <serial>6816515</serial>
        </baseInfo>
        <deviceType>integrated</deviceType>
        <origin>China</origin>
        <release>2020-10</release>
        <price>70</price>
        <isCritical>true</isCritical>
        <size>16</size>
        <power>55</power>
        <isCooler>false</isCooler>
    </GraphicsCard>
    <GraphicsCard id="d9">
        <name>graphicCard4</name>
        <baseInfo>
            <producer>EVGA</producer>
            <model>gtx3060</model>
            <serial>3453974</serial>
        </baseInfo>
        <deviceType>integrated</deviceType>
        <origin>Singopore</origin>
        <release>2020-04</release>
        <price>65</price>
        <isCritical>true</isCritical>
        <size>32</size>
        <power>50</power>
        <isCooler>false</isCooler>
    </GraphicsCard>
    <GraphicsCard id="d10">
        <name>graphicCard5</name>
        <baseInfo>
            <producer>Asus</producer>
            <model>gtx940</model>
            <serial>96754</serial>
        </baseInfo>
        <deviceType>integrated</deviceType>
        <origin>China</origin>
        <release>2020-06</release>
        <price>50</price>
        <isCritical>true</isCritical>
        <size>2</size>
        <power>40</power>
        <isCooler>true</isCooler>
    </GraphicsCard>

    <Mouse id="d11">
        <name>mouse1</name>
        <baseInfo>
            <producer>Smartby</producer>
            <model>43335</model>
            <serial>427867867</serial>
        </baseInfo>
        <deviceType>peripheral</deviceType>
        <origin>China</origin>
        <release>2021-02</release>
        <price>10</price>
        <isCritical>false</isCritical>
        <portType>usb</portType>
        <connectionType>wireless</connectionType>
    </Mouse>
    <Mouse id="d12">
        <name>mouse2</name>
        <baseInfo>
            <producer>Defender</producer>
            <model>D6545</model>
            <serial>86405</serial>
        </baseInfo>
        <deviceType>peripheral</deviceType>
        <origin>China</origin>
        <release>2021-03</release>
        <price>5</price>
        <isCritical>false</isCritical>
        <portType>usb</portType>
        <connectionType>wired</connectionType>
    </Mouse>
    <Mouse id="d13">
        <name>mouse3</name>
        <baseInfo>
            <producer>Logitech</producer>
            <model>L68535</model>
            <serial>123552</serial>
        </baseInfo>
        <deviceType>peripheral</deviceType>
        <origin>China</origin>
        <release>2021-04</release>
        <price>7</price>
        <isCritical>false</isCritical>
        <portType>ps_2</portType>
        <connectionType>wired</connectionType>
    </Mouse>
    <Mouse id="d14">
        <name>mouse4</name>
        <baseInfo>
            <producer>Defender</producer>
            <model>D234</model>
            <serial>836537</serial>
        </baseInfo>
        <deviceType>peripheral</deviceType>
        <origin>China</origin>
        <release>2021-05</release>
        <price>6</price>
        <isCritical>false</isCritical>
        <portType>usb</portType>
        <connectionType>wired</connectionType>
    </Mouse>
    <Mouse id="d15">
        <name>mouse5</name>
        <baseInfo>
            <producer>Logitech</producer>
            <model>L342</model>
            <serial>5675</serial>
        </baseInfo>
        <deviceType>peripheral</deviceType>
        <origin>China</origin>
        <release>2021-06</release>
        <price>6</price>
        <isCritical>false</isCritical>
        <portType>usb</portType>
        <connectionType>wireless</connectionType>
    </Mouse>
</Devices>
